.gitignore, src/App.css, src/App.js, src/index.css
=> Css styles

src/App.css, src/containers/App/index.js
@grady-lad: I just added some more style changes. Could you review and merge?
=> Fix stylings

package.json, src/utils/index.js
Added moment.js and date functions (today's date + last week's date) to utils.
=> Add Moment.js and date functions

package.json, src/containers/App/index.js, src/utils/request.js
=> Fix fetch issues

src/App.css, src/components/List/ListItem.js, src/components/List/ListWrapper.js, src/components/TimeChoiceHeader/index.js
When you click "Week" "Month" "Year" or "All" it gives the link an active class and stays highlighted.
=> Add active state to time header

src/components/List/ListWrapper.js
Added new props on `list-wrapper` component to fix the issue of links not being displayed in the footer.
=> Amend props on list wrapper

package.json, src/App.css, src/components/TeamItem/index.js, src/constants/index.js, src/containers/App/index.js, src/containers/Team/index.js, src/index.js, src/routes/index.js
Add new team page to url `/team`
(Issue #13)
=> Add Team page

.eslintrc, package.json, src/analytics.js, src/components/Footer/index.js, src/components/Header/index.js, src/components/InfoColumn/index.js, src/components/List/ListItem.js, src/components/List/ListWrapper.js, src/components/Resources/index.js, src/components/TimeChoiceHeader/index.js, src/components/index.js, src/constants/index.js, src/containers/App/index.js, src/containers/App/tests/App.test.js, src/data/index.js, src/index.js, src/utils/index.js, src/utils/request.js
1. Added eslint and configured to project. Linting can now be run with the script `npm run lint`.
2. Added Jest for testing which can be run with the script `npm run test`.
3. Linted the whole project.
=> Add and configure eslint & add Jest

src/constants/index.js
=> Add my Github picture

src/App.css, src/containers/App/index.js
Header, footer and nav bar are now all responsive on mobile.
=> Made header, footer and nav bar responsive on mobile

src/App.css, src/constants/index.js
Fixed: 
- team grid spacing issues (issue #13)
- team image links for Firefox (issue #53)
- "Global Co2" heading on footer now links back to frontpage
=> Fixed team image links and grid spacing

src/App.css
Footer heading spacing was not aligned on small screens. Fixed 👍
=> Fix footer header spacing

package.json
Due to this [issue](https://github.com/moment/moment/issues/4216)
=> Fixing depedency version of moment due to webpack issue

package.json, src/App.css, src/analytics.js, src/components/Loading/index.js, src/components/PpmChart/index.js, src/components/Svg/index.js, src/components/index.js, src/containers/ChartInfo/index.js, src/utils/index.js
- Introduced react 16
- Halved the All data as SVG struggles to render all of the objects
- Throttle and debounce events to reduce closest point calculation
- Binary Search elements so that it is more scalable
- Use universal ga as react-ga no longer works due to react 16
- Improve loading div appearance
=> Chart cleanup

src/containers/ChartInfo/index.js
- Use ALL as initial req
- Refactor fetch logic
=> Refactored chart fetching

.eslintrc, src/App.css, src/components/Header/index.js, src/constants/index.js, src/containers/About/index.js, src/containers/Contribute/index.js, src/containers/DataSources/index.js, src/containers/Team/index.js, src/utils/index.js
- Add **+** and **-** to PPM and % figures
- Style fixes on team, about, contribute pages
- Fixed height of footer
- Added new header
=> Add + and - signs to chart and style fixes

src/App.css, src/components/PpmChart/index.js, src/components/ToolTip/ToolTip.css, src/components/ToolTip/index.js, src/containers/ChartInfo/index.js
- Fixed tool-tip colours/styles and added the "PPM" (issue #93)
- Changed the border colours (issue #85)
- Fixed the loading div height so it stops flashing when the graph loads
- Graph-filler and flex-grid border (issue #94)
- Chart Range menu colouring (issue #92)
- Implement Proxima Nova font (issue #91)
=> Fix Tool Tip and loading div

src/utils/index.js
Use every 10th item when rendering 'All' data
=> Using 10th of all data

src/utils/index.js
=> Sampling by week for ALL

src/components/Footer/footer.css, src/components/Footer/index.js
=> Reduce footer width

src/containers/ChartInfo/utils/index.js, src/containers/ChartInfo/utils/tests/index.test.js
This PR should fix https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/156.
=> 156: Use decimals for the graph instead of whole numbers.

src/constants/index.js
=> Fix typo in "Work with us".

src/components/InfoCardSection/index.js
=> Link to data sources section of the Github wiki.
